
package mFinanceUI;
import java.awt.*;
import javax.swing.JLayeredPane;
public class AutoLoanCategories extends javax.swing.JPanel {
    private JLayeredPane jLayeredPane;

    /**
     * Creates new form AutoLoanCategories
     */
    public AutoLoanCategories(JLayeredPane j) {
        initComponents();
        setVisible(true);
        jLayeredPane = j;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autoLoanRadioButtons = new javax.swing.ButtonGroup();
        AutoLoanHeader = new javax.swing.JLabel();
        NewCarLoanRadioButton = new javax.swing.JRadioButton();
        UsedCarRadioButton = new javax.swing.JRadioButton();
        OtherLoanRadioButton = new javax.swing.JRadioButton();
        AutoLoanApplyButton = new javax.swing.JButton();
        AutoRefinanceRadioButton = new javax.swing.JRadioButton();
        AutoLoanBackButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        AutoLoanHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        AutoLoanHeader.setText("Auto Loans");

        NewCarLoanRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        autoLoanRadioButtons.add(NewCarLoanRadioButton);
        NewCarLoanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NewCarLoanRadioButton.setText("New Car Loan");
        NewCarLoanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCarLoanRadioButtonActionPerformed(evt);
            }
        });

        UsedCarRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        autoLoanRadioButtons.add(UsedCarRadioButton);
        UsedCarRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UsedCarRadioButton.setText("Used Car Loan");
        UsedCarRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsedCarRadioButtonActionPerformed(evt);
            }
        });

        OtherLoanRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        autoLoanRadioButtons.add(OtherLoanRadioButton);
        OtherLoanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OtherLoanRadioButton.setText("Motorcycle, Boat, Other Loans");

        AutoLoanApplyButton.setBackground(new java.awt.Color(255, 255, 255));
        AutoLoanApplyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AutoLoanApplyButton.setText("Apply Now");
        AutoLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoLoanApplyButtonActionPerformed(evt);
            }
        });

        AutoRefinanceRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        autoLoanRadioButtons.add(AutoRefinanceRadioButton);
        AutoRefinanceRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AutoRefinanceRadioButton.setText("Refinance Auto Loan");

        AutoLoanBackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AutoLoanBackButton.setText("Back");
        AutoLoanBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoLoanBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AutoLoanBackButton)
                        .addGap(315, 315, 315)
                        .addComponent(AutoLoanHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AutoRefinanceRadioButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(OtherLoanRadioButton)
                        .addComponent(UsedCarRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NewCarLoanRadioButton, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AutoLoanApplyButton)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AutoLoanBackButton)
                    .addComponent(AutoLoanHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(NewCarLoanRadioButton)
                .addGap(58, 58, 58)
                .addComponent(UsedCarRadioButton)
                .addGap(59, 59, 59)
                .addComponent(OtherLoanRadioButton)
                .addGap(60, 60, 60)
                .addComponent(AutoRefinanceRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 440, Short.MAX_VALUE)
                .addComponent(AutoLoanApplyButton)
                .addGap(118, 118, 118))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NewCarLoanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCarLoanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewCarLoanRadioButtonActionPerformed

    private void AutoLoanBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoLoanBackButtonActionPerformed
        // TODO add your handling code here:
        ProductUi productUI = new ProductUi(jLayeredPane);
        jLayeredPane.removeAll();
        jLayeredPane.add(productUI);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }//GEN-LAST:event_AutoLoanBackButtonActionPerformed

    private void AutoLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoLoanApplyButtonActionPerformed
        // TODO add your handling code here:
        ApplicationForm applicationForm = new ApplicationForm(jLayeredPane);
        jLayeredPane.removeAll();
        jLayeredPane.add(applicationForm);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }//GEN-LAST:event_AutoLoanApplyButtonActionPerformed

    private void UsedCarRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsedCarRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsedCarRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AutoLoanApplyButton;
    private javax.swing.JButton AutoLoanBackButton;
    private javax.swing.JLabel AutoLoanHeader;
    private javax.swing.JRadioButton AutoRefinanceRadioButton;
    private javax.swing.JRadioButton NewCarLoanRadioButton;
    private javax.swing.JRadioButton OtherLoanRadioButton;
    private javax.swing.JRadioButton UsedCarRadioButton;
    private javax.swing.ButtonGroup autoLoanRadioButtons;
    // End of variables declaration//GEN-END:variables
}
