
package mFinanceUI;
import java.awt.*;
import javax.swing.JLayeredPane;
public class AutoLoanCategories extends javax.swing.JPanel {
    private JLayeredPane jLayeredPane;

    /**
     * Creates new form AutoLoanCategories
     */
    public AutoLoanCategories(JLayeredPane j) {
        initComponents();
        setVisible(true);
        jLayeredPane = j;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autoLoanRadioButtons = new javax.swing.ButtonGroup();
        AutoLoanHeader = new javax.swing.JLabel();
        NewCarLoanRadioButton = new javax.swing.JRadioButton();
        UsedCarRadioButton = new javax.swing.JRadioButton();
        OtherLoanRadioButton = new javax.swing.JRadioButton();
        AutoLoanApplyButton = new javax.swing.JButton();
        AutoRefinanceRadioButton = new javax.swing.JRadioButton();
        AutoLoanBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        AutoLoanHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        AutoLoanHeader.setText("Auto Loans");

        NewCarLoanRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        autoLoanRadioButtons.add(NewCarLoanRadioButton);
        NewCarLoanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NewCarLoanRadioButton.setText("New Car Loan");
        NewCarLoanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCarLoanRadioButtonActionPerformed(evt);
            }
        });

        UsedCarRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        autoLoanRadioButtons.add(UsedCarRadioButton);
        UsedCarRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UsedCarRadioButton.setText("Used Car Loan");
        UsedCarRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsedCarRadioButtonActionPerformed(evt);
            }
        });

        OtherLoanRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        autoLoanRadioButtons.add(OtherLoanRadioButton);
        OtherLoanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OtherLoanRadioButton.setText("Motorcycle, Boat, Other Loans");

        AutoLoanApplyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AutoLoanApplyButton.setText("Apply Now");
        AutoLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoLoanApplyButtonActionPerformed(evt);
            }
        });

        AutoRefinanceRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        autoLoanRadioButtons.add(AutoRefinanceRadioButton);
        AutoRefinanceRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AutoRefinanceRadioButton.setText("Refinance Auto Loan");

        AutoLoanBackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AutoLoanBackButton.setText("Back");
        AutoLoanBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoLoanBackButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Rates as low as 2.99%\n**Rates vary depending on credit score and loan term");
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setEditable(false);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Rates as low as 3.99%");
        jScrollPane2.setViewportView(jTextArea2);
        jTextArea2.setEditable(false);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Rates as low as 6.25%");
        jScrollPane3.setViewportView(jTextArea3);
        jTextArea3.setEditable(false);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Save on your monthly payments by refinancing your auto loan. Rates as low as 3.25%");
        jScrollPane4.setViewportView(jTextArea4);
        jTextArea4.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AutoLoanApplyButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(AutoRefinanceRadioButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(AutoLoanBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(178, 178, 178)
                            .addComponent(AutoLoanHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OtherLoanRadioButton)
                            .addComponent(UsedCarRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewCarLoanRadioButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutoLoanHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AutoLoanBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(NewCarLoanRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsedCarRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OtherLoanRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AutoRefinanceRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(AutoLoanApplyButton)
                .addContainerGap(257, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NewCarLoanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCarLoanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewCarLoanRadioButtonActionPerformed

    private void AutoLoanBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoLoanBackButtonActionPerformed
        // TODO add your handling code here:
        ProductUi productUI = new ProductUi(jLayeredPane);
        jLayeredPane.removeAll();
        jLayeredPane.add(productUI);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }//GEN-LAST:event_AutoLoanBackButtonActionPerformed

    private void AutoLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoLoanApplyButtonActionPerformed
        // TODO add your handling code here:
        ApplicationForm applicationForm = new ApplicationForm(jLayeredPane);
        jLayeredPane.removeAll();
        jLayeredPane.add(applicationForm);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }//GEN-LAST:event_AutoLoanApplyButtonActionPerformed

    private void UsedCarRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsedCarRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsedCarRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AutoLoanApplyButton;
    private javax.swing.JButton AutoLoanBackButton;
    private javax.swing.JLabel AutoLoanHeader;
    private javax.swing.JRadioButton AutoRefinanceRadioButton;
    private javax.swing.JRadioButton NewCarLoanRadioButton;
    private javax.swing.JRadioButton OtherLoanRadioButton;
    private javax.swing.JRadioButton UsedCarRadioButton;
    private javax.swing.ButtonGroup autoLoanRadioButtons;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
