
package mFinanceUI;
import java.awt.*;
import javax.swing.JLayeredPane;
public class AutoLoanCategories extends javax.swing.JPanel {
    private JLayeredPane jLayeredPane;

    /**
     * Creates new form AutoLoanCategories
     */
    public AutoLoanCategories(JLayeredPane j) {
        initComponents();
        setVisible(true);
        jLayeredPane = j;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AutoLoanHeader = new javax.swing.JLabel();
        NerCarLoanRadioButton = new javax.swing.JRadioButton();
        UsedCarRadioButton = new javax.swing.JRadioButton();
        OtherLoanRadioButton = new javax.swing.JRadioButton();
        AutoLoanApplyButton = new javax.swing.JButton();
        AutoRefinanceRadioButton = new javax.swing.JRadioButton();
        AutoLoanBackButton = new javax.swing.JButton();

        AutoLoanHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        AutoLoanHeader.setText("Auto Loans");

        NerCarLoanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NerCarLoanRadioButton.setText("New Car Loan");
        NerCarLoanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NerCarLoanRadioButtonActionPerformed(evt);
            }
        });

        UsedCarRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UsedCarRadioButton.setText("Used Car Loan");

        OtherLoanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OtherLoanRadioButton.setText("Motorcycle, Boat, Other Loans");

        AutoLoanApplyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AutoLoanApplyButton.setText("Apply Now");

        AutoRefinanceRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AutoRefinanceRadioButton.setText("Refinance Auto Loan");

        AutoLoanBackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AutoLoanBackButton.setText("Back");
        AutoLoanBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoLoanBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AutoLoanBackButton)
                        .addGap(315, 315, 315)
                        .addComponent(AutoLoanHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AutoRefinanceRadioButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(OtherLoanRadioButton)
                        .addComponent(UsedCarRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NerCarLoanRadioButton, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AutoLoanApplyButton)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AutoLoanBackButton)
                    .addComponent(AutoLoanHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(NerCarLoanRadioButton)
                .addGap(58, 58, 58)
                .addComponent(UsedCarRadioButton)
                .addGap(59, 59, 59)
                .addComponent(OtherLoanRadioButton)
                .addGap(60, 60, 60)
                .addComponent(AutoRefinanceRadioButton)
                .addGap(120, 120, 120)
                .addComponent(AutoLoanApplyButton)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NerCarLoanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NerCarLoanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NerCarLoanRadioButtonActionPerformed

    private void AutoLoanBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoLoanBackButtonActionPerformed
        // TODO add your handling code here:
        ProductUi productUI = new ProductUi(jLayeredPane);
        jLayeredPane.removeAll();
        jLayeredPane.add(productUI);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }//GEN-LAST:event_AutoLoanBackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AutoLoanApplyButton;
    private javax.swing.JButton AutoLoanBackButton;
    private javax.swing.JLabel AutoLoanHeader;
    private javax.swing.JRadioButton AutoRefinanceRadioButton;
    private javax.swing.JRadioButton NerCarLoanRadioButton;
    private javax.swing.JRadioButton OtherLoanRadioButton;
    private javax.swing.JRadioButton UsedCarRadioButton;
    // End of variables declaration//GEN-END:variables
}
