/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * https://www.nerdwallet.com/blog/small-business/types-of-business-loans/
 */
package mFinanceUI;

/**
 *
 * @author Parker
 */
import javax.swing.JLayeredPane;
public class BusinessLoanCategories extends javax.swing.JPanel {

    /**
     * Creates new form BusinessLoanCategories
     */
    public BusinessLoanCategories(JLayeredPane j) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        termLoanApplyButton = new javax.swing.JButton();
        sbaLoanApplyButton = new javax.swing.JButton();
        lineOfCreditApplyButton = new javax.swing.JButton();
        invoiceFinancingApplyButton = new javax.swing.JButton();
        cashAdvanceApplyButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Business Loans");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Term Loan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Small Business Administration (SBA) Loan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Business Line of Credit");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Invoice Financing Loan");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Merchant Cash Advances");

        termLoanApplyButton.setText("Apply Now");
        termLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termLoanApplyButtonActionPerformed(evt);
            }
        });

        sbaLoanApplyButton.setText("Apply Now");
        sbaLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbaLoanApplyButtonActionPerformed(evt);
            }
        });

        lineOfCreditApplyButton.setText("Apply Now");
        lineOfCreditApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineOfCreditApplyButtonActionPerformed(evt);
            }
        });

        invoiceFinancingApplyButton.setText("Apply Now");
        invoiceFinancingApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceFinancingApplyButtonActionPerformed(evt);
            }
        });

        cashAdvanceApplyButton.setText("Apply Now");
        cashAdvanceApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashAdvanceApplyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(termLoanApplyButton)
                            .addComponent(sbaLoanApplyButton)
                            .addComponent(lineOfCreditApplyButton)
                            .addComponent(invoiceFinancingApplyButton)
                            .addComponent(cashAdvanceApplyButton))
                        .addGap(234, 234, 234))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2)
                                                .addComponent(termLoanApplyButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addComponent(sbaLoanApplyButton))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(lineOfCreditApplyButton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(invoiceFinancingApplyButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(cashAdvanceApplyButton))
                .addContainerGap(279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void termLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termLoanApplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termLoanApplyButtonActionPerformed

    private void sbaLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbaLoanApplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbaLoanApplyButtonActionPerformed

    private void lineOfCreditApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineOfCreditApplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineOfCreditApplyButtonActionPerformed

    private void invoiceFinancingApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceFinancingApplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceFinancingApplyButtonActionPerformed

    private void cashAdvanceApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashAdvanceApplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashAdvanceApplyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cashAdvanceApplyButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton invoiceFinancingApplyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton lineOfCreditApplyButton;
    private javax.swing.JButton sbaLoanApplyButton;
    private javax.swing.JButton termLoanApplyButton;
    // End of variables declaration//GEN-END:variables
}
