/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * https://www.nerdwallet.com/blog/small-business/types-of-business-loans/
 */
package mFinanceUI;

/**
 *
 * @author Parker
 */
import javax.swing.JLayeredPane;
public class BusinessLoanCategories extends javax.swing.JPanel {
    private JLayeredPane jLayeredPane;
    /**
     * Creates new form BusinessLoanCategories
     */
    public BusinessLoanCategories(JLayeredPane j) {
        initComponents();
        setVisible(true);
        jLayeredPane = j;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        businessLoanRadioButtons = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        BusinessLoanApplyButton = new javax.swing.JButton();
        BusinessLoanBackButton = new javax.swing.JButton();
        TermLoanRadioButton = new javax.swing.JRadioButton();
        SBALoanRadioButton = new javax.swing.JRadioButton();
        LineOfCreditRadioButton = new javax.swing.JRadioButton();
        InvoiceFinancingRadioButton = new javax.swing.JRadioButton();
        MerchantCashAdvancesRadioButton = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Business Loans");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BusinessLoanApplyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BusinessLoanApplyButton.setText("Apply Now");
        BusinessLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusinessLoanApplyButtonActionPerformed(evt);
            }
        });

        BusinessLoanBackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BusinessLoanBackButton.setText("Back");
        BusinessLoanBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusinessLoanBackButtonActionPerformed(evt);
            }
        });

        TermLoanRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        businessLoanRadioButtons.add(TermLoanRadioButton);
        TermLoanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TermLoanRadioButton.setText("Term Loan");

        SBALoanRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        businessLoanRadioButtons.add(SBALoanRadioButton);
        SBALoanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SBALoanRadioButton.setText("Small Business Administration (SBA) Loan");

        LineOfCreditRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        businessLoanRadioButtons.add(LineOfCreditRadioButton);
        LineOfCreditRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LineOfCreditRadioButton.setText("Business Line of Credit");

        InvoiceFinancingRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        businessLoanRadioButtons.add(InvoiceFinancingRadioButton);
        InvoiceFinancingRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InvoiceFinancingRadioButton.setText("Invoice Financing Loan");

        MerchantCashAdvancesRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        businessLoanRadioButtons.add(MerchantCashAdvancesRadioButton);
        MerchantCashAdvancesRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MerchantCashAdvancesRadioButton.setText("Merchant Cash Advances");
        MerchantCashAdvancesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MerchantCashAdvancesRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SBALoanRadioButton)
                    .addComponent(TermLoanRadioButton)
                    .addComponent(LineOfCreditRadioButton)
                    .addComponent(InvoiceFinancingRadioButton)
                    .addComponent(MerchantCashAdvancesRadioButton))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BusinessLoanBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BusinessLoanApplyButton)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BusinessLoanBackButton))
                .addGap(18, 18, 18)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(TermLoanRadioButton)
                .addGap(44, 44, 44)
                .addComponent(SBALoanRadioButton)
                .addGap(53, 53, 53)
                .addComponent(LineOfCreditRadioButton)
                .addGap(51, 51, 51)
                .addComponent(InvoiceFinancingRadioButton)
                .addGap(53, 53, 53)
                .addComponent(MerchantCashAdvancesRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(BusinessLoanApplyButton)
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BusinessLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusinessLoanApplyButtonActionPerformed
        // TODO add your handling code here:
        ApplicationForm applicationForm = new ApplicationForm(jLayeredPane);
        jLayeredPane.removeAll();
        jLayeredPane.add(applicationForm);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }//GEN-LAST:event_BusinessLoanApplyButtonActionPerformed

    private void BusinessLoanBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusinessLoanBackButtonActionPerformed
        // TODO add your handling code here:
        ProductUi productUI = new ProductUi(jLayeredPane);
        jLayeredPane.removeAll();
        jLayeredPane.add(productUI);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }//GEN-LAST:event_BusinessLoanBackButtonActionPerformed

    private void MerchantCashAdvancesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MerchantCashAdvancesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MerchantCashAdvancesRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusinessLoanApplyButton;
    private javax.swing.JButton BusinessLoanBackButton;
    private javax.swing.JRadioButton InvoiceFinancingRadioButton;
    private javax.swing.JRadioButton LineOfCreditRadioButton;
    private javax.swing.JRadioButton MerchantCashAdvancesRadioButton;
    private javax.swing.JRadioButton SBALoanRadioButton;
    private javax.swing.JRadioButton TermLoanRadioButton;
    private javax.swing.ButtonGroup businessLoanRadioButtons;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
