/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mFinanceUI;

/**
 *
 * @author Gonzales
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loanProductsMenu = new javax.swing.JMenu();
        viewProductsMenyItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Callisto mFinance System");

        fileMenu.setText("File");
        fileMenu.setToolTipText("Application Settings");
        menuBar.add(fileMenu);

        loanProductsMenu.setText("Loan Products");
        loanProductsMenu.setToolTipText("Menu that contains everything related to all\nthe Loan Products that Callisto has to offer");

        viewProductsMenyItem.setText("View Loan Products");
        viewProductsMenyItem.setToolTipText("Displays all the Loan Products that Callisto has to offer");
        viewProductsMenyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductsMenyItemActionPerformed(evt);
            }
        });
        loanProductsMenu.add(viewProductsMenyItem);

        menuBar.add(loanProductsMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewProductsMenyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductsMenyItemActionPerformed
        // TODO add your handling code to show the Products panel here
    }//GEN-LAST:event_viewProductsMenyItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu loanProductsMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem viewProductsMenyItem;
    // End of variables declaration//GEN-END:variables
}
