/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mFinanceUI;

import java.util.ArrayList;
import javax.swing.JLayeredPane;
import javax.swing.table.DefaultTableModel;
import mFinanceLoanManagement.Payment;
import mFinanceLoanManagement.PaymentList;
import mFinanceUserInformation.Customer;

/**
 *
 * @author gillj
 */
public class PaymentUi extends javax.swing.JPanel {

    String user;
    
    /**
     * Creates new form PaymentUi
     */
    public PaymentUi(JLayeredPane j , String username) {
        initComponents();
        user = username;
        addRowToJTable();
    }
    
    
        public void addRowToJTable() {
        DefaultTableModel model = (DefaultTableModel) loansTable.getModel();
        PaymentList paymentList = new PaymentList();
        ArrayList<Payment> list = paymentList.getPaymentList(user);
        Object[] rowData = new Object[2];
        if(list != null){
            for(int i = 0; i < list.size(); i++) {
                rowData[0] = list.get(i).getLoanNumber();                
                rowData[1] = list.get(i).getAmount();
                //rowData[2] = list.get(i).getDate();
                model.addRow(rowData);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentsLabel = new javax.swing.JLabel();
        paymentsTableJScrollPane = new javax.swing.JScrollPane();
        loansTable = new javax.swing.JTable();
        paymentFotmButton = new javax.swing.JButton();

        setBackground(java.awt.Color.white);

        paymentsLabel.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        paymentsLabel.setText("Payments");

        loansTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        loansTable.getTableHeader().setReorderingAllowed(false);
        paymentsTableJScrollPane.setViewportView(loansTable);
        if (loansTable.getColumnModel().getColumnCount() > 0) {
            loansTable.getColumnModel().getColumn(0).setResizable(false);
            loansTable.getColumnModel().getColumn(1).setResizable(false);
        }

        paymentFotmButton.setText("Payment Form");
        paymentFotmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentFotmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(paymentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paymentFotmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentsTableJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(paymentsLabel)
                .addGap(18, 18, 18)
                .addComponent(paymentsTableJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paymentFotmButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void paymentFotmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentFotmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentFotmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable loansTable;
    private javax.swing.JButton paymentFotmButton;
    private javax.swing.JLabel paymentsLabel;
    private javax.swing.JScrollPane paymentsTableJScrollPane;
    // End of variables declaration//GEN-END:variables
}
