/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * https://www.nerdwallet.com/blog/loans/personal-loan-types/
 */
package mFinanceUI;

/**
 *
 * @author Parker
 */
import javax.swing.JLayeredPane;
public class PersonalLoanCategories extends javax.swing.JPanel {

    /**
     * Creates new form PersonalLoanCategories
     */
    public PersonalLoanCategories(JLayeredPane j) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fixedRateLoanApplyButton = new javax.swing.JButton();
        variableRateLoanApplyButton = new javax.swing.JButton();
        debtConsolidationLoanApplyButton = new javax.swing.JButton();
        coSignLoanApplyButton = new javax.swing.JButton();
        personalLineOfCreditLoanApplyButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 600));
        setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Personal Loans");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        fixedRateLoanApplyButton.setText("Apply Now");
        fixedRateLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedRateLoanApplyButtonActionPerformed(evt);
            }
        });

        variableRateLoanApplyButton.setText("Apply Now");
        variableRateLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variableRateLoanApplyButtonActionPerformed(evt);
            }
        });

        debtConsolidationLoanApplyButton.setText("Apply Now");
        debtConsolidationLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debtConsolidationLoanApplyButtonActionPerformed(evt);
            }
        });

        coSignLoanApplyButton.setText("Apply Now");
        coSignLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coSignLoanApplyButtonActionPerformed(evt);
            }
        });

        personalLineOfCreditLoanApplyButton.setText("Apply Now");
        personalLineOfCreditLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalLineOfCreditLoanApplyButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Variable-Rate Loan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Debt Consolidation Loan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Co-Sign Loan");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Personal Line of Credit");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Fixed-Rate Loan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(288, 288, 288)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fixedRateLoanApplyButton)
                                    .addComponent(variableRateLoanApplyButton)
                                    .addComponent(debtConsolidationLoanApplyButton)
                                    .addComponent(coSignLoanApplyButton)
                                    .addComponent(personalLineOfCreditLoanApplyButton))))
                        .addGap(0, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(fixedRateLoanApplyButton))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addComponent(variableRateLoanApplyButton))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(debtConsolidationLoanApplyButton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(coSignLoanApplyButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(personalLineOfCreditLoanApplyButton))
                .addContainerGap(252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fixedRateLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedRateLoanApplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fixedRateLoanApplyButtonActionPerformed

    private void variableRateLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableRateLoanApplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_variableRateLoanApplyButtonActionPerformed

    private void debtConsolidationLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debtConsolidationLoanApplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debtConsolidationLoanApplyButtonActionPerformed

    private void coSignLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coSignLoanApplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coSignLoanApplyButtonActionPerformed

    private void personalLineOfCreditLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalLineOfCreditLoanApplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalLineOfCreditLoanApplyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coSignLoanApplyButton;
    private javax.swing.JButton debtConsolidationLoanApplyButton;
    private javax.swing.JButton fixedRateLoanApplyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton personalLineOfCreditLoanApplyButton;
    private javax.swing.JButton variableRateLoanApplyButton;
    // End of variables declaration//GEN-END:variables
}
