/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mFinanceUI;

/**
 *
 * @author Parker
 */
import javax.swing.JLayeredPane;
public class StudentLoanCategories extends javax.swing.JPanel {
    private JLayeredPane jLayeredPane;
    /**
     * Creates new form StudentLoansCategories
     */
    public StudentLoanCategories(JLayeredPane j) {
        initComponents();
        setVisible(true);
        jLayeredPane = j;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        privateStudentLoanApplyButton = new javax.swing.JButton();
        DirectSubsidizedRadioButton = new javax.swing.JRadioButton();
        DirectUnsubsidizedRadioButton = new javax.swing.JRadioButton();
        DirectPlusRadioButton = new javax.swing.JRadioButton();
        DirectConsolidationRadioButton = new javax.swing.JRadioButton();
        PrivateStudentRadioButton = new javax.swing.JRadioButton();
        StudentLoanBackButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Loans");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        privateStudentLoanApplyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        privateStudentLoanApplyButton.setText("Apply Now");
        privateStudentLoanApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privateStudentLoanApplyButtonActionPerformed(evt);
            }
        });

        DirectSubsidizedRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        DirectSubsidizedRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DirectSubsidizedRadioButton.setText("Direct Subsidized Loan");

        DirectUnsubsidizedRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        DirectUnsubsidizedRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DirectUnsubsidizedRadioButton.setText("Direct Unsubsidized Loan");
        DirectUnsubsidizedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectUnsubsidizedRadioButtonActionPerformed(evt);
            }
        });

        DirectPlusRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        DirectPlusRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DirectPlusRadioButton.setText("Direct PLUS Loan");

        DirectConsolidationRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        DirectConsolidationRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DirectConsolidationRadioButton.setText("Direct Consolidation Loan");
        DirectConsolidationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectConsolidationRadioButtonActionPerformed(evt);
            }
        });

        PrivateStudentRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        PrivateStudentRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrivateStudentRadioButton.setText("Private Student Loan");
        PrivateStudentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrivateStudentRadioButtonActionPerformed(evt);
            }
        });

        StudentLoanBackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StudentLoanBackButton.setText("Back");
        StudentLoanBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentLoanBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(privateStudentLoanApplyButton)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StudentLoanBackButton)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PrivateStudentRadioButton)
                    .addComponent(DirectUnsubsidizedRadioButton)
                    .addComponent(DirectSubsidizedRadioButton)
                    .addComponent(DirectPlusRadioButton)
                    .addComponent(DirectConsolidationRadioButton))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentLoanBackButton))
                .addGap(45, 45, 45)
                .addComponent(DirectSubsidizedRadioButton)
                .addGap(53, 53, 53)
                .addComponent(DirectUnsubsidizedRadioButton)
                .addGap(55, 55, 55)
                .addComponent(DirectPlusRadioButton)
                .addGap(53, 53, 53)
                .addComponent(DirectConsolidationRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(PrivateStudentRadioButton)
                .addGap(46, 46, 46)
                .addComponent(privateStudentLoanApplyButton)
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void privateStudentLoanApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privateStudentLoanApplyButtonActionPerformed
        // TODO add your handling code here:
        ApplicationForm applicationForm = new ApplicationForm(jLayeredPane);
        jLayeredPane.removeAll();
        jLayeredPane.add(applicationForm);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }//GEN-LAST:event_privateStudentLoanApplyButtonActionPerformed

    private void DirectConsolidationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectConsolidationRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirectConsolidationRadioButtonActionPerformed

    private void PrivateStudentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrivateStudentRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrivateStudentRadioButtonActionPerformed

    private void StudentLoanBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentLoanBackButtonActionPerformed
        // TODO add your handling code here:
        ProductUi productUI = new ProductUi(jLayeredPane);
        jLayeredPane.removeAll();
        jLayeredPane.add(productUI);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }//GEN-LAST:event_StudentLoanBackButtonActionPerformed

    private void DirectUnsubsidizedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectUnsubsidizedRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirectUnsubsidizedRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DirectConsolidationRadioButton;
    private javax.swing.JRadioButton DirectPlusRadioButton;
    private javax.swing.JRadioButton DirectSubsidizedRadioButton;
    private javax.swing.JRadioButton DirectUnsubsidizedRadioButton;
    private javax.swing.JRadioButton PrivateStudentRadioButton;
    private javax.swing.JButton StudentLoanBackButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton privateStudentLoanApplyButton;
    // End of variables declaration//GEN-END:variables
}
